name: p_webview
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.8.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  screen_adaptation:
    path: ../screen_adaptation
  p_image_loader:
    path: ../p_image_loader
  p_utils:
    path: ../p_utils
    
flutter: