name: p_img_compress
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_image_compress: ^1.1.0
  p_widget:
    path: ../p_widget
  path_provider: ^2.0.5
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
