name: p_img_compress
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.8.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_image_compress: ^0.7.0
  p_widget:
    path: ../p_widget
  path_provider: ^1.6.22
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
