name: p_utils
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  launch_review: ^3.0.1
  url_launcher: ^6.0.2
  fluttertoast: ^7.1.8
  device_info: ^2.0.0
  package_info: ^2.0.0
  devicelocale: ^0.4.0
  crypto: ^3.0.0
  shared_preferences: ^2.0.4
  hex: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
