name: p_utils
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  launch_review: ^3.0.1
  url_launcher: ^6.0.12
  fluttertoast: ^8.0.8
  device_info: ^2.0.2
  package_info: ^2.0.2
  devicelocale: ^0.5.0
  crypto: ^3.0.1
  shared_preferences: ^2.0.8
  hex: ^0.2.0
  simple_logger: ^1.8.1+1
  clipboard: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
