name: p_image_loader
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.19.1
  cached_network_image: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
