name: p_widget
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  p_utils:
    path: ../p_utils

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: