name: p_rpc
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  messagepack: ^0.1.2
  encrypt: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  p_utils:
    path: ../p_utils
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter: